services:
  - type: web
    name: yt-whisper-api
    env: python
    buildCommand: bash build.sh
    startCommand: ./main -m models/ggml-base.en.bin -f /tmp/audio.wav
    envVars:
      - key: PORT
        value: 10000
